/** Sample packs and chat copy for registry types that open as a face. */

export const FACES = {
  emf: {
    title: "Intent",
    file: "intent.emf.prim", size: "199 B",
    preview: "Human intent stays here.",
    open: "Don’t send the notes.",
    offer: "Send the intent prim. The face cites that file.",
    after: "This is the memory. The pack stays put.",
    heading: "Intent",
    body: "A human-intent prim. What someone meant, kept as a file.",
  },
  orf: {
    title: "Research",
    file: "inquiry.orf.prim", size: "212 B",
    preview: "The inquiry is the pack.",
    open: "Don’t send the binder.",
    offer: "Send the research prim.",
    after: "Claims stay in the file. The face just opens it.",
    heading: "Inquiry",
    body: "A research prim. The investigation is this pack, not a slide dump.",
  },
  opf: {
    title: "Product",
    file: "atlas.opf.prim", size: "196 B",
    preview: "The product graph is the file.",
    open: "Don’t send the roadmap deck.",
    offer: "Send the product prim.",
    after: "The graph is in the pack. This is the face.",
    heading: "Atlas",
    body: "A product prim. Nodes and edges live in the file.",
  },
  odwf: {
    title: "Proof",
    file: "slice.odwf.prim", size: "202 B",
    preview: "Spreadsheet to bronze proof.",
    open: "Don’t send the workbook.",
    offer: "Send the proof prim.",
    after: "The proof is the pack. The table is a view.",
    heading: "Slice",
    body: "A proof prim. The workbook became a file you can cite.",
  },
  opff: {
    title: "Finance",
    file: "house.opff.prim", size: "7.8 KB",
    preview: "Household numbers stay in the pack.",
    open: "Don’t send the bank CSV.",
    offer: "Send the finance prim. The ledger is a view of that file.",
    after: "The ledger is in the rail. Ask for budget, cash, or spending — chat still points it.",
    heading: "House",
    body: "A household ledger. Charts cite the pack — they aren’t a copy.",
  },
  omf: {
    title: "Meetings",
    file: "june.omf.prim", size: "203 B",
    preview: "Occurrences, not a calendar export.",
    open: "Don’t send the calendar.",
    offer: "Send the meeting prim.",
    after: "Each occurrence is in the file.",
    heading: "June 12",
    body: "A meeting prim. The occurrence is the pack, not the invite.",
  },
  ocsf: {
    title: "Corporate",
    file: "harbor.ocsf.prim", size: "215 B",
    preview: "Ownership stays in the file.",
    open: "Don’t send the cap-table PDF.",
    offer: "Send the corporate prim.",
    after: "Structure and capital are in the pack.",
    heading: "Harbor",
    body: "A corporate prim. Ownership, capital, governance — this file.",
  },
  obif: {
    title: "Brand",
    file: "mark.obif.prim", size: "204 B",
    preview: "The brand prim is the source.",
    open: "Don’t send the brand zip.",
    offer: "Send the brand prim.",
    after: "Mark, type, voice — cited from this pack.",
    heading: "Mark",
    body: "A brand prim. Identity lives in the file, not a drive folder.",
  },
  osf: {
    title: "OSF",
    file: "june.osf.prim", size: "208 B",
    preview: "Open Session Format. Not the thin session.",
    open: "Don’t paste the transcript.",
    offer: "Send the OSF prim.",
    after: "This is the movable session pack. The other session chat is the thin file.",
    heading: "June 12",
    body: "An Open Session Format prim. A session that can move as a pack.",
  },
  obf: {
    title: "Private",
    file: "keep.obf.prim", size: "207 B",
    preview: "Private / emerging.",
    open: "This one stays closed.",
    offer: "Send the private prim if you hold it.",
    after: "The face opens. The contents stay yours.",
    heading: "Keep",
    body: "A private prim. Listed so the family is complete. No payload here.",
  },
};
